name: Trigger Repo Update

on:
  push:
    branches:
      - main

jobs:
  repo-update:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch to Parent
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: john-dunglao-dev/portfolio-docker
          event-type: react-submodule-updated
          client-payload: '{"submodule": "${{ github.repository }}", "sha": "${{ github.sha }}"}'
