name: Trigger Repo Update

on:
  push:
    branches:
      - main

jobs:
  repo_update:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch to Parent
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: submodule_updated
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
          repository: john-dunglao-dev/portfolio-docker
          client-payload: '{"sha": "${{ github.sha }}"}'
